version: '1.0'

services:
  frontend:
    container_name: frontend
    env_file: .env
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./src:/frontend/src
      - type: bind
        source: ./package.json
        target: /frontend/package.json
      - type: bind
        source: ./package-lock.json
        target: /frontend/package-lock.json
    # command: ng serve --host 0.0.0.0
    ports:
      - "4200:4200"
